"""FarmAI Activity Register — Phase 5 Farmer Experience. Read-only; no Stock writes."""
from datetime import date,timedelta
from ..db import connection
from .activity_register import ActivityRegisterNotFound
def _ds(x): return [dict(r) for r in x]
def farmer_dashboard(farm_id=None,crop_cycle_id=None,date_from=None,date_to=None):
    today=date.today(); date_from=date_from or today-timedelta(days=30); date_to=date_to or today+timedelta(days=14)
    with connection() as c:
        farm=c.execute("SELECT * FROM public.farms WHERE "+("id=%s" if farm_id else "active=true ORDER BY created_at LIMIT 1"),((farm_id,) if farm_id else ())).fetchone()
        if not farm: raise ActivityRegisterNotFound("Farm not found. (शेत सापडले नाही.)")
        cycles=_ds(c.execute("""SELECT cc.id crop_cycle_id,cc.cycle_code,cc.crop_name_en,cc.crop_name_mr,cc.variety_en,cc.variety_mr,cc.status,cc.planting_date,cc.dap_baseline_date,cc.dap_baseline_type,cc.area,cc.area_unit_code,p.code plot_code,p.name_en plot_name_en,p.name_mr plot_name_mr FROM public.crop_cycles cc JOIN public.plots p ON p.id=cc.plot_id WHERE cc.farm_id=%s AND (%s::uuid IS NULL OR cc.id=%s) ORDER BY (cc.status='ACTIVE') DESC,cc.crop_name_en""",(farm["id"],crop_cycle_id,crop_cycle_id)).fetchall())
        ids=[x["crop_cycle_id"] for x in cycles]
        if not ids:return {"as_of_date":today,"farm":dict(farm),"summary":{"active_crop_cycles":0,"overdue":0,"today":0,"upcoming":0,"completed_last_30_days":0},"crop_cycles":[],"work_queue":[],"recent_history":[]}
        work=_ds(c.execute("""SELECT a.id activity_id,a.crop_cycle_id,a.status,a.planned_date,a.scheduled_date,a.planned_dap,a.name_en,a.name_mr,at.code activity_type_code,at.name_en activity_type_name_en,at.name_mr activity_type_name_mr,cc.crop_name_en,cc.crop_name_mr,p.code plot_code,p.name_en plot_name_en,p.name_mr plot_name_mr,COALESCE(a.scheduled_date,a.planned_date,a.created_at::date) effective_date,(COALESCE(a.scheduled_date,a.planned_date,a.created_at::date)-cc.dap_baseline_date) effective_dap,(SELECT count(*) FROM public.activity_inputs ai WHERE ai.activity_id=a.id) planned_input_count FROM public.activities a JOIN public.activity_types at ON at.id=a.activity_type_id JOIN public.crop_cycles cc ON cc.id=a.crop_cycle_id JOIN public.plots p ON p.id=cc.plot_id WHERE a.crop_cycle_id=ANY(%s) AND a.status NOT IN ('COMPLETED','SKIPPED','CANCELLED') AND COALESCE(a.scheduled_date,a.planned_date,a.created_at::date)<=%s ORDER BY effective_date""",(ids,date_to)).fetchall())
        for x in work:
            x["bucket"]="OVERDUE" if x["effective_date"]<today else ("TODAY" if x["effective_date"]==today else "UPCOMING")
            x["display_label_en"]=x["name_en"] or x["activity_type_name_en"];x["display_label_mr"]=x["name_mr"] or x["activity_type_name_mr"]
        hist=_ds(c.execute("""SELECT a.id activity_id,a.crop_cycle_id,ae.id execution_id,ae.execution_date,ae.dap_at_execution,ae.pump_count,at.code activity_type_code,at.name_en activity_type_name_en,at.name_mr activity_type_name_mr,cc.crop_name_en,cc.crop_name_mr,p.code plot_code,p.name_en plot_name_en,p.name_mr plot_name_mr,(SELECT count(*) FROM public.activity_execution_inputs i WHERE i.execution_id=ae.id) actual_input_count,(SELECT count(*) FROM public.activity_execution_inputs i WHERE i.execution_id=ae.id AND i.stock_sync_status='SYNCED') stock_synced_input_count,(SELECT count(*) FROM public.activity_execution_inputs i WHERE i.execution_id=ae.id AND i.stock_sync_status='REVERSED') stock_reversed_input_count FROM public.activity_executions ae JOIN public.activities a ON a.id=ae.activity_id JOIN public.activity_types at ON at.id=a.activity_type_id JOIN public.crop_cycles cc ON cc.id=a.crop_cycle_id JOIN public.plots p ON p.id=cc.plot_id WHERE a.crop_cycle_id=ANY(%s) AND ae.status='COMPLETED' AND ae.execution_date BETWEEN %s AND %s ORDER BY ae.execution_date DESC LIMIT 100""",(ids,date_from,today)).fetchall())
        for x in cycles:
            x["current_dap"]=(today-x["dap_baseline_date"]).days if x["dap_baseline_date"] else None;x["pending_activity_count"]=sum(w["crop_cycle_id"]==x["crop_cycle_id"] for w in work);x["completed_in_window"]=sum(h["crop_cycle_id"]==x["crop_cycle_id"] for h in hist)
        return {"as_of_date":today,"window":{"history_from":date_from,"history_to":today,"upcoming_to":date_to},"farm":dict(farm),"summary":{"active_crop_cycles":sum(x["status"]=="ACTIVE" for x in cycles),"overdue":sum(x["bucket"]=="OVERDUE" for x in work),"today":sum(x["bucket"]=="TODAY" for x in work),"upcoming":sum(x["bucket"]=="UPCOMING" for x in work),"completed_last_30_days":len(hist)},"crop_cycles":cycles,"work_queue":work,"recent_history":hist}
def crop_activity_timeline(crop_cycle_id,limit=200):
    with connection() as c:
        cycle=c.execute("""SELECT cc.*,f.name_en farm_name_en,f.name_mr farm_name_mr,p.code plot_code,p.name_en plot_name_en,p.name_mr plot_name_mr FROM public.crop_cycles cc JOIN public.farms f ON f.id=cc.farm_id JOIN public.plots p ON p.id=cc.plot_id WHERE cc.id=%s""",(crop_cycle_id,)).fetchone()
        if not cycle:raise ActivityRegisterNotFound("Crop Cycle not found. (पीक चक्र सापडले नाही.)")
        rows=_ds(c.execute("""SELECT a.id activity_id,a.status activity_status,a.planned_date,a.scheduled_date,a.planned_dap,a.name_en,a.name_mr,at.code activity_type_code,at.name_en activity_type_name_en,at.name_mr activity_type_name_mr,ae.id execution_id,ae.execution_date,ae.status execution_status,ae.dap_at_execution,ae.pump_count,COALESCE(ae.execution_date,a.scheduled_date,a.planned_date,a.created_at::date) event_date FROM public.activities a JOIN public.activity_types at ON at.id=a.activity_type_id LEFT JOIN public.activity_executions ae ON ae.activity_id=a.id WHERE a.crop_cycle_id=%s ORDER BY event_date DESC LIMIT %s""",(crop_cycle_id,limit)).fetchall())
        for r in rows:
            r["display_label_en"]=r["name_en"] or r["activity_type_name_en"];r["display_label_mr"]=r["name_mr"] or r["activity_type_name_mr"];r["dap"]=r["dap_at_execution"] if r["dap_at_execution"] is not None else r["planned_dap"]
            r["purposes"]=_ds(c.execute("""SELECT ap.code,ap.name_en,ap.name_mr FROM public.activity_purpose_links l JOIN public.activity_purposes ap ON ap.id=l.activity_purpose_id WHERE l.activity_id=%s ORDER BY ap.sort_order""",(r["activity_id"],)).fetchall())
            if r["execution_id"]:r["products"]=_ds(c.execute("""SELECT p.product_code,p.product_name product_name_en,pdm.product_name_mr,i.actual_dose,i.actual_dose_unit_code,i.dose_basis_code,i.actual_total_quantity,i.actual_total_unit_code,i.stock_sync_status FROM public.activity_execution_inputs i JOIN public.products p ON p.id=i.product_id LEFT JOIN public.product_display_metadata pdm ON pdm.product_id=p.id WHERE i.execution_id=%s ORDER BY i.created_at""",(r["execution_id"],)).fetchall())
            else:r["products"]=_ds(c.execute("""SELECT p.product_code,p.product_name product_name_en,pdm.product_name_mr,i.planned_dose,i.planned_dose_unit_code,i.dose_basis_code,i.planned_total_quantity,i.planned_total_unit_code,i.stock_reservation_status FROM public.activity_inputs i JOIN public.products p ON p.id=i.product_id LEFT JOIN public.product_display_metadata pdm ON pdm.product_id=p.id WHERE i.activity_id=%s ORDER BY i.sequence_no""",(r["activity_id"],)).fetchall())
        return {"crop_cycle":dict(cycle),"timeline":rows}
